
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf NomPrenom.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ec2-13-38-111-17.eu-west-3.compute.amazonaws.com }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ 22}}
        source: "NomPrenom.war"
        target: "/opt/tomcat/webapps"
